apiVersion: v1
kind: Pod
metadata:
   name: app
   labels:
     name: app
spec:
  hostNetwork: true
  containers:
   - name: app
     image: docker.io/library/my-app:latest
     imagePullPolicy: Never     
    
